using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Cogwheel;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UIElements;

public class Test : MonoBehaviour
{
    private void Start()
    {
        var settings = COGWHEEL.Settings;
    }

    [Command(CommandName = "private", Description = "This is a private command")]
    private void PrivateCommand(int value, string text, float f)
    {
        Debug.Log($"PrivateCommand called: int is {value} and string is {text} and float is {f}");
    }

    [Command]
    private void What()
    {
        COGWHEEL.Log("WHAT");
    }
}
